
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # Do the builds on all pull requests (to test them)
  pull_request: []

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag face-detection-for-python-Demo:$GITHUB_SHA
    - name: Push the Docker image
      run: docker push ghcr.io/MeraX/face-detection-for-python-Demo:$GITHUB_SHA
