
name: Export sif

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: [main]
    types: 
      - completed

permissions:
  packages: write

jobs:
  to-sif:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: quay.io/singularity/singularity:v3.8.3
    strategy:
      fail-fast: false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo "Using $(singularity version)"

        echo "${GITHUB_TOKEN}" | singularity remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io

        export IMAGE_NAME=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')

        singularity pull docker://ghcr.io/${IMAGE_NAME}:${GITHUB_SHA}
        singularity push *.sif oras://ghcr.io/${IMAGE_NAME}:sif_${GITHUB_SHA}
